# permissions for end users to view berglassecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: berglassecret-viewer-role
rules:
- apiGroups:
  - batch.kitagry.github.io
  resources:
  - berglassecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.kitagry.github.io
  resources:
  - berglassecrets/status
  verbs:
  - get
