# permissions for end users to edit berglassecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: berglassecret-editor-role
rules:
- apiGroups:
  - batch.kitagry.github.io
  resources:
  - berglassecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.kitagry.github.io
  resources:
  - berglassecrets/status
  verbs:
  - get
