name: Test

on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go mod download

    - name: Test
      run: |
        curl -L https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.2/kubebuilder_2.3.2_$(go env GOOS)_$(go env GOARCH).tar.gz | sudo tar zx -C .
        mv kubebuilder_2.3.2_$(go env GOOS)_$(go env GOARCH) kubebuilder
        KUBEBUILDER_ASSETS=$(pwd)/kubebuilder/bin go test -v ./...
